version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
platform:
- x86
- x64
- ARM
before_build:
- cmd: pushd . && cd HN.Social.Weibo && nuget restore && popd
build:
  verbosity: minimal