name: CI
on: 
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Run build script
      run: .\build.ps1
      shell: pwsh