name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
    
    - name: MSBuild
      run: msbuild HN.Social.Weibo.sln /t:restore
